[package]
name = "cosmwasm-ica"
authors = ["j0nl1 <jonlitech@gmail.com>"]
version = "0.1.0"
edition = "2021"
description = "A library for facilitating IBC communication of Wasm based smart contracts on Cosmos blockchains"
repository = "https://github.com/j0nl1/cosmwasm-ica"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.1.0", features = ["ibc3"] }
cosmwasm-schema = { version = "1.1.4" }
thiserror = { version = "1.0.37" }